server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_animatch
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect


cloud:
  aws:
    region:
      static: ${S3_SERVER_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: debug
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

app:
  jwt-secret: ${JWT_KEY}


