-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 22:57:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_animatch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_animatch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_animatch` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_animatch` ;

-- -----------------------------------------------------
-- Table `db_animatch`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `created_date` DATE NOT NULL,
  `updated_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`location` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 22:57:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_animatch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_animatch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_animatch` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_animatch` ;

-- -----------------------------------------------------
-- Table `db_animatch`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(255) NOT NULL,
  `created_date` DATE NOT NULL,
  `updated_date` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`location` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`pet` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pure_race` BIT NOT NULL,
  `id_location` BIGINT NOT NULL,
  `age` INT NOT NULL,
  `animal_type` ENUM('CAT', 'DOG') NOT NULL,
  `race` VARCHAR(100) NOT NULL,
  `size` ENUM('BIG', 'MEDIUM', 'SHORT') NOT NULL,
  `gender` ENUM('FEMALE', 'MALE') NOT NULL,
  `vaccinations_up_to_date` BIT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pet_location_idx` (`id_location` ASC) VISIBLE,
  CONSTRAINT `fk_pet_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `db_animatch`.`location` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`picture` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` BLOB NOT NULL,
  `content_type` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`pet_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`pet_picture` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `id_pet` BIGINT NOT NULL,
  `id_picture` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pp_pet_idx` (`id_pet` ASC) VISIBLE,
  INDEX `fk_pp_picture_idx` (`id_picture` ASC) VISIBLE,
  CONSTRAINT `fk_pp_pet`
    FOREIGN KEY (`id_pet`)
    REFERENCES `db_animatch`.`pet` (`id`),
  CONSTRAINT `fk_pp_picture`
    FOREIGN KEY (`id_picture`)
    REFERENCES `db_animatch`.`picture` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`user_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`user_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT NOT NULL,
  `id_comment` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_uc_comment_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_uc_user_idx` (`id_comment` ASC) VISIBLE,
  CONSTRAINT `fk_uc_comment`
    FOREIGN KEY (`id_comment`)
    REFERENCES `db_animatch`.`comment` (`id`),
  CONSTRAINT `fk_uc_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_animatch`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_animatch`.`user_pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_animatch`.`user_pet` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `id_user` BIGINT NOT NULL,
  `id_pet` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_up_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_up_pet_idx` (`id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_up_pet`
    FOREIGN KEY (`id_pet`)
    REFERENCES `db_animatch`.`pet` (`id`),
  CONSTRAINT `fk_up_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_animatch`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;